> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Numpy functions at random

Write a short introduction about Numpy and list the chosen functions. 

- Trigonometric Sine
- Power
- Sort
- Search
- Mean

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [4]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [54]:
# List of functions explained 
function1 = np.sin 
function2 = np.power
function3 = np.sort
function4 = np.where
function5 = np.mean

## Function 1 - np.sin

Helps find element-wise sine of an array.

In [14]:
# Example 1 - working
arr1 = np.array([0., 30., 45., 60., 90.])
np.sin(arr1*np.pi/180.)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

The sine of the values is returned.

In [17]:
# Example 2 - working
arr2 = np.sin(np.array([np.pi, np.pi/2., np.pi/4, np.pi/3, np.pi/6]))
arr2

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 8.66025404e-01,
       5.00000000e-01])

Sine with the input values in radian.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
x=3
np.sin(np.array([0., 30., 45., 60., 90.]),out=x)

TypeError: return arrays must be of ArrayType

The attribute out specifies the location where the output is stored. Here, the output is aimed to be stored in x which is an integer. Thus, the TypeError is raised. We can store it in a an array instead.

Some closing comments about when to use this function.

In [20]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

## Function 2 - np.power

First array elements raised to powers from second array, element-wise.

In [23]:
# Example 1 - working
arr1=np.array([1,2,3,4,5])
np.power(arr1,4)

array([  1,  16,  81, 256, 625])

Returns the 4th power of the values in the array.

In [25]:
# Example 2 - working
arr2=np.array([5,4,3,2,1])
np.power(arr1,arr2)

array([ 1, 16, 27, 16,  5])

Elements in the first array raised to the power of the values in the second array.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.array([4,-4])
np.power(arr3,-2)

ValueError: Integers to negative integer powers are not allowed.

The negative integer power of a number is tried to be computed. 

Some closing comments about when to use this function.

In [30]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

## Function 3 - np.sort

Return a sorted copy of an array.

In [31]:
# Example 1 - working
np.sort(np.array([56,39,0,48,-2]))

array([-2,  0, 39, 48, 56])

Sorts the array.

In [40]:
# Example 2 - working
np.sort(np.array([[56,39,0,48,-2],[3,7,10,-10,6]]),axis=0)

array([[  3,   7,   0, -10,  -2],
       [ 56,  39,  10,  48,   6]])

Sorted along the first axis. Default being the last axis.

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
np.sort(np.array([[56,39,0,48,-2],[3,7,10,-10,6]]),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

The Axis index is beyond the number of dimensions of the array. We must change the axis index inorder to avoid the error.

Some closing comments about when to use this function.

In [42]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

## Function 4 - np.where

Return elements chosen from x or y depending on condition.

In [46]:
# Example 1 - working
arr1=np.arange(15)
np.where(arr1<9,arr1,arr1*2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 18, 20, 22, 24, 26, 28])

Finding elements less than 7 and doubling the rest.

In [47]:
# Example 2 - working
arr2=np.arange(15)
np.where(arr2%2==0)

(array([ 0,  2,  4,  6,  8, 10, 12, 14]),)

Extracts the even elements in an array

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
arr3=np.arange(15)
np.where(arr3%2==0,arr3<0)

ValueError: either both or neither of x and y should be given

I have mentioned either x or y. Both must be mentioned for the function to have some meaning.

Some closing comments about when to use this function.

In [53]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

## Function 5 - np.mean

Compute the arithmetic mean along the specified axis.

In [58]:
# Example 1 - working
np.mean(np.arange(1,11))

5.5

Computed the mean of the first 10 natural numbers

In [59]:
# Example 2 - working
np.mean(np.array([[1, 2], [3, 4]]), axis=0)

array([2., 3.])

Find the mean of the matrix along the first axis.

In [60]:
# Example 3 - breaking (to illustrate when it breaks)
np.mean(np.array([[1, 2], [3, 4]]), axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

We try to calculate the mean of the matrix along an axis beyond the dimensions of the matrix. We must change the axis index inorder to avoid the error.

Some closing comments about when to use this function.

In [61]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [62]:
jovian.commit(filename='numpy-array-operations.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "f20201371/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/f20201371/numpy-array-operations


'https://jovian.ai/f20201371/numpy-array-operations'